package com.dev.XRPTools_JaveEE.View;

import com.dev.XRPTools_JaveEE.Model.createXRPWallet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.PrintWriter;

public class Display extends HttpServlet {
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException{
        resp.setContentType("text/html");
        PrintWriter out = resp.getWriter();
        createXRPWallet wallet = (createXRPWallet)
        req.getAttribute("xrpwallet");

        out.println("<html lang=\"en\"><!--begin::Head--><head><base href=\"\">");
        out.println("	<meta charset=\"utf-8\">");
        out.println("	<title>Metronic Bootstrap 5 Theme | Keenthemes</title>");
        out.println("	<meta name=\"description\" content=\"Metronic admin dashboard live demo. Check out all the features of the admin panel. A large number of settings, additional services and widgets.\">");
        out.println("	<meta name=\"keywords\" content=\"Metronic, bootstrap, bootstrap 5, Angular 11, VueJs, React, Laravel, admin themes, web design, figma, web development, ree admin themes, bootstrap admin, bootstrap dashboard\">");
        out.println("	<link rel=\"canonical\" href=\"Https://preview.keenthemes.com/metronic8\">");
        out.println("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        out.println("	<link rel=\"shortcut icon\" href=\"assets/media/logos/favicon.ico\">");
        out.println("	<!--begin::Fonts-->");
        out.println("	<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\">");
        out.println("	<!--end::Fonts-->");
        out.println("	<!--begin::Global Stylesheets Bundle(used by all pages)-->");
        out.println("	<link href=\"assets/plugins/global/plugins.bundle.css\" rel=\"stylesheet\" type=\"text/css\">");
        out.println("	<link href=\"assets/css/style.bundle.css\" rel=\"stylesheet\" type=\"text/css\">");
        out.println("	<!--end::Global Stylesheets Bundle-->");
        out.println("<style type=\"text/css\">.apexcharts-canvas {");
        out.println(" position: relative;");
        out.println(" user-select: none;");
        out.println(" /* cannot give overflow: hidden as it will crop tooltips which overflow outside chart area */");
        out.println("");
        out.println("");
        out.println("* scrollbar is not visible by default for legend, hence forcing the visibility */");
        out.println("apexcharts-canvas ::-webkit-scrollbar {");
        out.println(" -webkit-appearance: none;");
        out.println(" width: 6px;");
        out.println("");
        out.println(".apexcharts-canvas ::-webkit-scrollbar-thumb {");
        out.println(" border-radius: 4px;");
        out.println(" background-color: rgba(0, 0, 0, .5);");
        out.println(" box-shadow: 0 0 1px rgba(255, 255, 255, .5);");
        out.println(" -webkit-box-shadow: 0 0 1px rgba(255, 255, 255, .5);");
        out.println("");
        out.println("");
        out.println("apexcharts-inner {");
        out.println(" position: relative;");
        out.println("");
        out.println(".apexcharts-text tspan {");
        out.println(" font-family: inherit;");
        out.println("");
        out.println(".legend-mouseover-inactive {");
        out.println(" transition: 0.15s ease all;");
        out.println(" opacity: 0.20;");
        out.println("");
        out.println(".apexcharts-series-collapsed {");
        out.println(" opacity: 0;");
        out.println("");
        out.println(".apexcharts-tooltip {");
        out.println(" border-radius: 5px;");
        out.println(" box-shadow: 2px 2px 6px -4px #999;");
        out.println(" cursor: default;");
        out.println(" font-size: 14px;");
        out.println(" left: 62px;");
        out.println(" opacity: 0;");
        out.println(" pointer-events: none;");
        out.println(" position: absolute;");
        out.println(" top: 20px;");
        out.println(" display: flex;");
        out.println(" flex-direction: column;");
        out.println(" overflow: hidden;");
        out.println(" white-space: nowrap;");
        out.println(" z-index: 12;");
        out.println(" transition: 0.15s ease all;");
        out.println("");
        out.println(".apexcharts-tooltip.apexcharts-active {");
        out.println(" opacity: 1;");
        out.println(" transition: 0.15s ease all;");
        out.println("");
        out.println(".apexcharts-tooltip.apexcharts-theme-light {");
        out.println(" border: 1px solid #e3e3e3;");
        out.println(" background: rgba(255, 255, 255, 0.96);");
        out.println("");
        out.println(".apexcharts-tooltip.apexcharts-theme-dark {");
        out.println(" color: #fff;");
        out.println(" background: rgba(30, 30, 30, 0.8);");
        out.println("");
        out.println(".apexcharts-tooltip * {");
        out.println(" font-family: inherit;");
        out.println("");
        out.println("");
        out.println("apexcharts-tooltip-title {");
        out.println(" padding: 6px;");
        out.println(" font-size: 15px;");
        out.println(" margin-bottom: 4px;");
        out.println("");
        out.println(".apexcharts-tooltip.apexcharts-theme-light .apexcharts-tooltip-title {");
        out.println(" background: #ECEFF1;");
        out.println(" border-bottom: 1px solid #ddd;");
        out.println("");
        out.println(".apexcharts-tooltip.apexcharts-theme-dark .apexcharts-tooltip-title {");
        out.println(" background: rgba(0, 0, 0, 0.7);");
        out.println(" border-bottom: 1px solid #333;");
        out.println("");
        out.println(".apexcharts-tooltip-text-value,");
        out.println("apexcharts-tooltip-text-z-value {");
        out.println(" display: inline-block;");
        out.println(" font-weight: 600;");
        out.println(" margin-left: 5px;");
        out.println("");
        out.println(".apexcharts-tooltip-text-z-label:empty,");
        out.println("apexcharts-tooltip-text-z-value:empty {");
        out.println(" display: none;");
        out.println("");
        out.println(".apexcharts-tooltip-text-value,");
        out.println("apexcharts-tooltip-text-z-value {");
        out.println(" font-weight: 600;");
        out.println("");
        out.println(".apexcharts-tooltip-marker {");
        out.println(" width: 12px;");
        out.println(" height: 12px;");
        out.println(" position: relative;");
        out.println(" top: 0px;");
        out.println(" margin-right: 10px;");
        out.println(" border-radius: 50%;");
        out.println("");
        out.println(".apexcharts-tooltip-series-group {");
        out.println(" padding: 0 10px;");
        out.println(" display: none;");
        out.println(" text-align: left;");
        out.println(" justify-content: left;");
        out.println(" align-items: center;");
        out.println("");
        out.println(".apexcharts-tooltip-series-group.apexcharts-active .apexcharts-tooltip-marker {");
        out.println(" opacity: 1;");
        out.println("");
        out.println(".apexcharts-tooltip-series-group.apexcharts-active,");
        out.println("apexcharts-tooltip-series-group:last-child {");
        out.println(" padding-bottom: 4px;");
        out.println("");
        out.println(".apexcharts-tooltip-series-group-hidden {");
        out.println(" opacity: 0;");
        out.println(" height: 0;");
        out.println(" line-height: 0;");
        out.println(" padding: 0 !important;");
        out.println("");
        out.println(".apexcharts-tooltip-y-group {");
        out.println(" padding: 6px 0 5px;");
        out.println("");
        out.println(".apexcharts-tooltip-candlestick {");
        out.println(" padding: 4px 8px;");
        out.println("");
        out.println(".apexcharts-tooltip-candlestick>div {");
        out.println(" margin: 4px 0;");
        out.println("");
        out.println(".apexcharts-tooltip-candlestick span.value {");
        out.println(" font-weight: bold;");
        out.println("");
        out.println(".apexcharts-tooltip-rangebar {");
        out.println(" padding: 5px 8px;");
        out.println("");
        out.println(".apexcharts-tooltip-rangebar .category {");
        out.println(" font-weight: 600;");
        out.println(" color: #777;");
        out.println("");
        out.println(".apexcharts-tooltip-rangebar .series-name {");
        out.println(" font-weight: bold;");
        out.println(" display: block;");
        out.println(" margin-bottom: 5px;");
        out.println("");
        out.println(".apexcharts-xaxistooltip {");
        out.println(" opacity: 0;");
        out.println(" padding: 9px 10px;");
        out.println(" pointer-events: none;");
        out.println(" color: #373d3f;");
        out.println(" font-size: 13px;");
        out.println(" text-align: center;");
        out.println(" border-radius: 2px;");
        out.println(" position: absolute;");
        out.println(" z-index: 10;");
        out.println(" background: #ECEFF1;");
        out.println(" border: 1px solid #90A4AE;");
        out.println(" transition: 0.15s ease all;");
        out.println("");
        out.println(".apexcharts-xaxistooltip.apexcharts-theme-dark {");
        out.println(" background: rgba(0, 0, 0, 0.7);");
        out.println(" border: 1px solid rgba(0, 0, 0, 0.5);");
        out.println(" color: #fff;");
        out.println("");
        out.println(".apexcharts-xaxistooltip:after,");
        out.println("apexcharts-xaxistooltip:before {");
        out.println(" left: 50%;");
        out.println(" border: solid transparent;");
        out.println(" content: \" \";");
        out.println(" height: 0;");
        out.println(" width: 0;");
        out.println(" position: absolute;");
        out.println(" pointer-events: none;");
        out.println("");
        out.println(".apexcharts-xaxistooltip:after {");
        out.println(" border-color: rgba(236, 239, 241, 0);");
        out.println(" border-width: 6px;");
        out.println(" margin-left: -6px;");
        out.println("");
        out.println(".apexcharts-xaxistooltip:before {");
        out.println(" border-color: rgba(144, 164, 174, 0);");
        out.println(" border-width: 7px;");
        out.println(" margin-left: -7px;");
        out.println("");
        out.println(".apexcharts-xaxistooltip-bottom:after,");
        out.println("apexcharts-xaxistooltip-bottom:before {");
        out.println(" bottom: 100%;");
        out.println("");
        out.println(".apexcharts-xaxistooltip-top:after,");
        out.println("apexcharts-xaxistooltip-top:before {");
        out.println(" top: 100%;");
        out.println("");
        out.println(".apexcharts-xaxistooltip-bottom:after {");
        out.println(" border-bottom-color: #ECEFF1;");
        out.println("");
        out.println(".apexcharts-xaxistooltip-bottom:before {");
        out.println(" border-bottom-color: #90A4AE;");
        out.println("");
        out.println(".apexcharts-xaxistooltip-bottom.apexcharts-theme-dark:after {");
        out.println(" border-bottom-color: rgba(0, 0, 0, 0.5);");
        out.println("");
        out.println(".apexcharts-xaxistooltip-bottom.apexcharts-theme-dark:before {");
        out.println(" border-bottom-color: rgba(0, 0, 0, 0.5);");
        out.println("");
        out.println(".apexcharts-xaxistooltip-top:after {");
        out.println(" border-top-color: #ECEFF1");
        out.println("");
        out.println(".apexcharts-xaxistooltip-top:before {");
        out.println(" border-top-color: #90A4AE;");
        out.println("");
        out.println(".apexcharts-xaxistooltip-top.apexcharts-theme-dark:after {");
        out.println(" border-top-color: rgba(0, 0, 0, 0.5);");
        out.println("");
        out.println(".apexcharts-xaxistooltip-top.apexcharts-theme-dark:before {");
        out.println(" border-top-color: rgba(0, 0, 0, 0.5);");
        out.println("");
        out.println(".apexcharts-xaxistooltip.apexcharts-active {");
        out.println(" opacity: 1;");
        out.println(" transition: 0.15s ease all;");
        out.println("");
        out.println(".apexcharts-yaxistooltip {");
        out.println(" opacity: 0;");
        out.println(" padding: 4px 10px;");
        out.println(" pointer-events: none;");
        out.println(" color: #373d3f;");
        out.println(" font-size: 13px;");
        out.println(" text-align: center;");
        out.println(" border-radius: 2px;");
        out.println(" position: absolute;");
        out.println(" z-index: 10;");
        out.println(" background: #ECEFF1;");
        out.println(" border: 1px solid #90A4AE;");
        out.println("");
        out.println(".apexcharts-yaxistooltip.apexcharts-theme-dark {");
        out.println(" background: rgba(0, 0, 0, 0.7);");
        out.println(" border: 1px solid rgba(0, 0, 0, 0.5);");
        out.println(" color: #fff;");
        out.println("");
        out.println(".apexcharts-yaxistooltip:after,");
        out.println("apexcharts-yaxistooltip:before {");
        out.println(" top: 50%;");
        out.println(" border: solid transparent;");
        out.println(" content: \" \";");
        out.println(" height: 0;");
        out.println(" width: 0;");
        out.println(" position: absolute;");
        out.println(" pointer-events: none;");
        out.println("");
        out.println(".apexcharts-yaxistooltip:after {");
        out.println(" border-color: rgba(236, 239, 241, 0);");
        out.println(" border-width: 6px;");
        out.println(" margin-top: -6px;");
        out.println("");
        out.println(".apexcharts-yaxistooltip:before {");
        out.println(" border-color: rgba(144, 164, 174, 0);");
        out.println(" border-width: 7px;");
        out.println(" margin-top: -7px;");
        out.println("");
        out.println(".apexcharts-yaxistooltip-left:after,");
        out.println("apexcharts-yaxistooltip-left:before {");
        out.println(" left: 100%;");
        out.println("");
        out.println(".apexcharts-yaxistooltip-right:after,");
        out.println("apexcharts-yaxistooltip-right:before {");
        out.println(" right: 100%;");
        out.println("");
        out.println(".apexcharts-yaxistooltip-left:after {");
        out.println(" border-left-color: #ECEFF1;");
        out.println("");
        out.println(".apexcharts-yaxistooltip-left:before {");
        out.println(" border-left-color: #90A4AE;");
        out.println("");
        out.println(".apexcharts-yaxistooltip-left.apexcharts-theme-dark:after {");
        out.println(" border-left-color: rgba(0, 0, 0, 0.5);");
        out.println("");
        out.println(".apexcharts-yaxistooltip-left.apexcharts-theme-dark:before {");
        out.println(" border-left-color: rgba(0, 0, 0, 0.5);");
        out.println("");
        out.println(".apexcharts-yaxistooltip-right:after {");
        out.println(" border-right-color: #ECEFF1;");
        out.println("");
        out.println(".apexcharts-yaxistooltip-right:before {");
        out.println(" border-right-color: #90A4AE;");
        out.println("");
        out.println(".apexcharts-yaxistooltip-right.apexcharts-theme-dark:after {");
        out.println(" border-right-color: rgba(0, 0, 0, 0.5);");
        out.println("");
        out.println(".apexcharts-yaxistooltip-right.apexcharts-theme-dark:before {");
        out.println(" border-right-color: rgba(0, 0, 0, 0.5);");
        out.println("");
        out.println(".apexcharts-yaxistooltip.apexcharts-active {");
        out.println(" opacity: 1;");
        out.println("");
        out.println(".apexcharts-yaxistooltip-hidden {");
        out.println(" display: none;");
        out.println("");
        out.println(".apexcharts-xcrosshairs,");
        out.println("apexcharts-ycrosshairs {");
        out.println(" pointer-events: none;");
        out.println(" opacity: 0;");
        out.println(" transition: 0.15s ease all;");
        out.println("");
        out.println(".apexcharts-xcrosshairs.apexcharts-active,");
        out.println("apexcharts-ycrosshairs.apexcharts-active {");
        out.println(" opacity: 1;");
        out.println(" transition: 0.15s ease all;");
        out.println("");
        out.println(".apexcharts-ycrosshairs-hidden {");
        out.println(" opacity: 0;");
        out.println("");
        out.println(".apexcharts-selection-rect {");
        out.println(" cursor: move;");
        out.println("");
        out.println(".svg_select_boundingRect, .svg_select_points_rot {");
        out.println(" pointer-events: none;");
        out.println(" opacity: 0;");
        out.println(" visibility: hidden;");
        out.println("");
        out.println("apexcharts-selection-rect + g .svg_select_boundingRect,");
        out.println("apexcharts-selection-rect + g .svg_select_points_rot {");
        out.println(" opacity: 0;");
        out.println(" visibility: hidden;");
        out.println("");
        out.println(".apexcharts-selection-rect + g .svg_select_points_l,");
        out.println("apexcharts-selection-rect + g .svg_select_points_r {");
        out.println(" cursor: ew-resize;");
        out.println(" opacity: 1;");
        out.println(" visibility: visible;");
        out.println("");
        out.println(".svg_select_points {");
        out.println(" fill: #efefef;");
        out.println(" stroke: #333;");
        out.println(" rx: 2;");
        out.println("");
        out.println(".apexcharts-svg.apexcharts-zoomable.hovering-zoom {");
        out.println(" cursor: crosshair");
        out.println("");
        out.println(".apexcharts-svg.apexcharts-zoomable.hovering-pan {");
        out.println(" cursor: move");
        out.println("");
        out.println(".apexcharts-zoom-icon,");
        out.println("apexcharts-zoomin-icon,");
        out.println("apexcharts-zoomout-icon,");
        out.println("apexcharts-reset-icon,");
        out.println("apexcharts-pan-icon,");
        out.println("apexcharts-selection-icon,");
        out.println("apexcharts-menu-icon,");
        out.println("apexcharts-toolbar-custom-icon {");
        out.println(" cursor: pointer;");
        out.println(" width: 20px;");
        out.println(" height: 20px;");
        out.println(" line-height: 24px;");
        out.println(" color: #6E8192;");
        out.println(" text-align: center;");
        out.println("");
        out.println(".apexcharts-zoom-icon svg,");
        out.println("apexcharts-zoomin-icon svg,");
        out.println("apexcharts-zoomout-icon svg,");
        out.println("apexcharts-reset-icon svg,");
        out.println("apexcharts-menu-icon svg {");
        out.println(" fill: #6E8192;");
        out.println("");
        out.println(".apexcharts-selection-icon svg {");
        out.println(" fill: #444;");
        out.println(" transform: scale(0.76)");
        out.println("");
        out.println(".apexcharts-theme-dark .apexcharts-zoom-icon svg,");
        out.println("apexcharts-theme-dark .apexcharts-zoomin-icon svg,");
        out.println("apexcharts-theme-dark .apexcharts-zoomout-icon svg,");
        out.println("apexcharts-theme-dark .apexcharts-reset-icon svg,");
        out.println("apexcharts-theme-dark .apexcharts-pan-icon svg,");
        out.println("apexcharts-theme-dark .apexcharts-selection-icon svg,");
        out.println("apexcharts-theme-dark .apexcharts-menu-icon svg,");
        out.println("apexcharts-theme-dark .apexcharts-toolbar-custom-icon svg {");
        out.println(" fill: #f3f4f5;");
        out.println("");
        out.println(".apexcharts-canvas .apexcharts-zoom-icon.apexcharts-selected svg,");
        out.println("apexcharts-canvas .apexcharts-selection-icon.apexcharts-selected svg,");
        out.println("apexcharts-canvas .apexcharts-reset-zoom-icon.apexcharts-selected svg {");
        out.println(" fill: #008FFB;");
        out.println("");
        out.println(".apexcharts-theme-light .apexcharts-selection-icon:not(.apexcharts-selected):hover svg,");
        out.println("apexcharts-theme-light .apexcharts-zoom-icon:not(.apexcharts-selected):hover svg,");
        out.println("apexcharts-theme-light .apexcharts-zoomin-icon:hover svg,");
        out.println("apexcharts-theme-light .apexcharts-zoomout-icon:hover svg,");
        out.println("apexcharts-theme-light .apexcharts-reset-icon:hover svg,");
        out.println("apexcharts-theme-light .apexcharts-menu-icon:hover svg {");
        out.println(" fill: #333;");
        out.println("");
        out.println(".apexcharts-selection-icon,");
        out.println("apexcharts-menu-icon {");
        out.println(" position: relative;");
        out.println("");
        out.println(".apexcharts-reset-icon {");
        out.println(" margin-left: 5px;");
        out.println("");
        out.println(".apexcharts-zoom-icon,");
        out.println("apexcharts-reset-icon,");
        out.println("apexcharts-menu-icon {");
        out.println(" transform: scale(0.85);");
        out.println("");
        out.println(".apexcharts-zoomin-icon,");
        out.println("apexcharts-zoomout-icon {");
        out.println(" transform: scale(0.7)");
        out.println("");
        out.println(".apexcharts-zoomout-icon {");
        out.println(" margin-right: 3px;");
        out.println("");
        out.println(".apexcharts-pan-icon {");
        out.println(" transform: scale(0.62);");
        out.println(" position: relative;");
        out.println(" left: 1px;");
        out.println(" top: 0px;");
        out.println("");
        out.println(".apexcharts-pan-icon svg {");
        out.println(" fill: #fff;");
        out.println(" stroke: #6E8192;");
        out.println(" stroke-width: 2;");
        out.println("");
        out.println(".apexcharts-pan-icon.apexcharts-selected svg {");
        out.println(" stroke: #008FFB;");
        out.println("");
        out.println(".apexcharts-pan-icon:not(.apexcharts-selected):hover svg {");
        out.println(" stroke: #333;");
        out.println("");
        out.println(".apexcharts-toolbar {");
        out.println(" position: absolute;");
        out.println(" z-index: 11;");
        out.println(" max-width: 176px;");
        out.println(" text-align: right;");
        out.println(" border-radius: 3px;");
        out.println(" padding: 0px 6px 2px 6px;");
        out.println(" display: flex;");
        out.println(" justify-content: space-between;");
        out.println(" align-items: center;");
        out.println("");
        out.println(".apexcharts-menu {");
        out.println(" background: #fff;");
        out.println(" position: absolute;");
        out.println(" top: 100%;");
        out.println(" border: 1px solid #ddd;");
        out.println(" border-radius: 3px;");
        out.println(" padding: 3px;");
        out.println(" right: 10px;");
        out.println(" opacity: 0;");
        out.println(" min-width: 110px;");
        out.println(" transition: 0.15s ease all;");
        out.println(" pointer-events: none;");
        out.println("");
        out.println(".apexcharts-menu.apexcharts-menu-open {");
        out.println(" opacity: 1;");
        out.println(" pointer-events: all;");
        out.println(" transition: 0.15s ease all;");
        out.println("");
        out.println(".apexcharts-menu-item {");
        out.println(" padding: 6px 7px;");
        out.println(" font-size: 12px;");
        out.println(" cursor: pointer;");
        out.println("");
        out.println(".apexcharts-theme-light .apexcharts-menu-item:hover {");
        out.println(" background: #eee;");
        out.println("");
        out.println(".apexcharts-theme-dark .apexcharts-menu {");
        out.println(" background: rgba(0, 0, 0, 0.7);");
        out.println(" color: #fff;");
        out.println("");
        out.println("@media screen and (min-width: 768px) {");
        out.println(" .apexcharts-canvas:hover .apexcharts-toolbar {");
        out.println("   opacity: 1;");
        out.println(" }");
        out.println("");
        out.println(".apexcharts-datalabel.apexcharts-element-hidden {");
        out.println(" opacity: 0;");
        out.println("");
        out.println(".apexcharts-pie-label,");
        out.println("apexcharts-datalabels,");
        out.println("apexcharts-datalabel,");
        out.println("apexcharts-datalabel-label,");
        out.println("apexcharts-datalabel-value {");
        out.println(" cursor: default;");
        out.println(" pointer-events: none;");
        out.println("");
        out.println(".apexcharts-pie-label-delay {");
        out.println(" opacity: 0;");
        out.println(" animation-name: opaque;");
        out.println(" animation-duration: 0.3s;");
        out.println(" animation-fill-mode: forwards;");
        out.println(" animation-timing-function: ease;");
        out.println("");
        out.println(".apexcharts-canvas .apexcharts-element-hidden {");
        out.println(" opacity: 0;");
        out.println("");
        out.println(".apexcharts-hide .apexcharts-series-points {");
        out.println(" opacity: 0;");
        out.println("");
        out.println(".apexcharts-gridline,");
        out.println("apexcharts-annotation-rect,");
        out.println("apexcharts-tooltip .apexcharts-marker,");
        out.println("apexcharts-area-series .apexcharts-area,");
        out.println("apexcharts-line,");
        out.println("apexcharts-zoom-rect,");
        out.println("apexcharts-toolbar svg,");
        out.println("apexcharts-area-series .apexcharts-series-markers .apexcharts-marker.no-pointer-events,");
        out.println("apexcharts-line-series .apexcharts-series-markers .apexcharts-marker.no-pointer-events,");
        out.println("apexcharts-radar-series path,");
        out.println("apexcharts-radar-series polygon {");
        out.println(" pointer-events: none;");
        out.println("");
        out.println("");
        out.println("* markers */");
        out.println(".apexcharts-marker {");
        out.println(" transition: 0.15s ease all;");
        out.println("");
        out.println("@keyframes opaque {");
        out.println(" 0% {");
        out.println("   opacity: 0;");
        out.println(" }");
        out.println(" 100% {");
        out.println("   opacity: 1;");
        out.println(" }");
        out.println("");
        out.println("");
        out.println("* Resize generated styles */");
        out.println("@keyframes resizeanim {");
        out.println(" from {");
        out.println("   opacity: 0;");
        out.println(" }");
        out.println(" to {");
        out.println("   opacity: 0;");
        out.println(" }");
        out.println("");
        out.println(".resize-triggers {");
        out.println(" animation: 1ms resizeanim;");
        out.println(" visibility: hidden;");
        out.println(" opacity: 0;");
        out.println("");
        out.println(".resize-triggers,");
        out.println("resize-triggers>div,");
        out.println("contract-trigger:before {");
        out.println(" content: \" \";");
        out.println(" display: block;");
        out.println(" position: absolute;");
        out.println(" top: 0;");
        out.println(" left: 0;");
        out.println(" height: 100%;");
        out.println(" width: 100%;");
        out.println(" overflow: hidden;");
        out.println("");
        out.println(".resize-triggers>div {");
        out.println(" background: #eee;");
        out.println(" overflow: auto;");
        out.println("");
        out.println(".contract-trigger:before {");
        out.println(" width: 200%;");
        out.println(" height: 200%;");
        out.println("</style></head>");
        out.println("<!--end::Head-->");
        out.println("<!--begin::Body-->");
        out.println("<body id=\"kt_body\" class=\"bg-white\" data-new-gr-c-s-check-loaded=\"8.875.0\" data-gr-ext-installed=\"\">");
        out.println("	<!--begin::Main-->");
        out.println("	<div class=\"d-flex flex-column flex-root\">");
        out.println("		<!--begin::Authentication - Sign-in -->");
        out.println("		<div class=\"d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed\" style=\"background-image: url(assets/media/illustrations/progress-hd.png)\">");
        out.println("			<!--begin::Content-->");
        out.println("			<div class=\"d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20\">");
        out.println("				<!--begin::Logo-->");
        out.println("				<a href=\"index.html\" class=\"mb-12\">");
        out.println("					<img alt=\"Logo\" src=\"assets/media/logos/logo-2-dark.svg\" class=\"h-45px\">");
        out.println("				</a>");
        out.println("				<!--end::Logo-->");
        out.println("				<!--begin::Wrapper-->");
        out.println("				<div class=\"w-lg-500px bg-white rounded shadow-sm p-10 p-lg-15 mx-auto\">");
        out.println("					<!--begin::Form-->");
        out.println("					<form class=\"form w-100 fv-plugins-bootstrap5 fv-plugins-framework\" novalidate=\"novalidate\" id=\"kt_sign_in_form\" action=\"#\">");
        out.println("						");
        out.println("						");
        out.println("						");
        out.println("						");
        out.println(wallet.getWalletAddress());
        out.println("						");
        out.println("						");
        out.println("						");
        out.println("						");
        out.println("						");
        out.println("						");
        out.println("						<!--ADD CODE HERE-->");
        out.println("					<div></div></form>");
        out.println("					<!--end::Form-->");
        out.println("				</div>");
        out.println("				<!--end::Wrapper-->");
        out.println("			</div>");
        out.println("			<!--end::Content-->");
        out.println("			<!--begin::Footer-->");
        out.println("			<div class=\"d-flex flex-center flex-column-auto p-10\">");
        out.println("				<!--begin::Links-->");
        out.println("				<div class=\"d-flex align-items-center fw-bold fs-6\">");
        out.println("					<a href=\"https://keenthemes.com/faqs\" class=\"text-muted text-hover-primary px-2\">About</a>");
        out.println("					<a href=\"mailto:support@keenthemes.com\" class=\"text-muted text-hover-primary px-2\">Contact</a>");
        out.println("					<a href=\"https://1.envato.market/EA4JP\" class=\"text-muted text-hover-primary px-2\">Contact Us</a>");
        out.println("				</div>");
        out.println("				<!--end::Links-->");
        out.println("			</div>");
        out.println("			<!--end::Footer-->");
        out.println("		</div>");
        out.println("		<!--end::Authentication - Sign-in-->");
        out.println("	</div>");
        out.println("	<!--end::Main-->");
        out.println("	<!--begin::Javascript-->");
        out.println("	<!--begin::Global Javascript Bundle(used by all pages)-->");
        out.println("	<script src=\"assets/plugins/global/plugins.bundle.js\"></script>");
        out.println("	<script src=\"assets/js/scripts.bundle.js\"></script>");
        out.println("	<!--end::Global Javascript Bundle-->");
        out.println("	<!--begin::Page Custom Javascript(used by this page)-->");
        out.println("	<script src=\"assets/js/custom/authentication/sign-in/general.js\"></script>");
        out.println("	<!--end::Page Custom Javascript-->");
        out.println("	<!--end::Javascript-->");
        out.println("");
        out.println("");
        out.println("svg id=\"SvgjsSvg1001\" width=\"2\" height=\"0\" xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:svgjs=\"http://svgjs.com/svgjs\" style=\"overflow: hidden; top: -100%; left: -100%; position: absolute; opacity: 0;\"><defs id=\"SvgjsDefs1002\"></defs><polyline id=\"SvgjsPolyline1003\" points=\"0,0\"></polyline><path id=\"SvgjsPath1004\" d=\"M0 0 \"></path></svg></body><!--end::Body--></html>");
        }
    }